### ISSUE TITLE
sticker voor jou!

### ISSUE THREAD

**Issue by SamaraFellaDina** [driezie/the-startup-responsive-interactieve-website#10]
Jou form ziet er echt erg proffesioneel.  Het lijkt net alsof ik al op de website zit van Enrise. Je hebt er al helemaal zicht op. Ik ben benieuwd hoe het eindresultaat eruit gaat zien.

![](https://media.giphy.com/media/lTRT00JKftYDwpAkw7/giphy.gif)

**Comment by driezie** [comment]
bedankt
