### ISSUE TITLE
Gebruik geen spaties in bestandsnamen.

### ISSUE THREAD

**Issue by rutgerkock** [driezie/the-startup-responsive-interactieve-website#12]
De foto's laden niet als ik de pagina open, heeft miscchien te maken met de bestandsnamen waar spaties in zitten.
https://github.com/driezie/the-startup-responsive-interactieve-website/blob/c757c86dacbe9f374bf56f7ed9bcc88661419380/index.html#L66

**Comment by driezie** [comment]
Oke bedankt voor de issue. Deze fout zal ik in de volgende commit toepassen!

Groetjes,
Jelte :)

**Comment by driezie** [comment]
> This issue has been fixed in commit 2213ad2 by @driezie
