### ISSUE TITLE
action attribute in de form is leeg en moet wel een waarde bevatten

### ISSUE THREAD

**Issue by Mossati** [driezie/the-startup-responsive-interactieve-website#14]

**Comment by driezie** [comment]
Ik had nog niet de functionaliteit van de formulier kunnen maken op de goeie manier. Deze zal ik voor de volgende commit toepassen.

Beschrijf even volgende keer door middel van de issue template wat de issue is bedankt!!!

Groetjes,
Jelte :)

**Comment by driezie** [comment]
> This issue has been fixed in commit 737593b  by @driezie
