### ISSUE TITLE
Form heeft geen functie

### ISSUE THREAD

**Issue by yassirog** [driezie/the-startup-responsive-interactieve-website#15]
![image](https://github.com/driezie/the-startup-responsive-interactieve-website/assets/144006281/0b292999-356e-413a-b4d1-dd4908e74f94)

Je form zijn "action" is leeg. Dit geeft een error aan, misschien is het een slim idee om "action" weg te halen aangezien het een dummy is.

**Comment by driezie** [comment]
Ik had nog niet de functionaliteit van de formulier kunnen maken op de goeie manier. Deze zal ik voor de volgende commit toepassen.

Beschrijf even volgende keer door middel van de issue template wat de issue is bedankt!!!

Groetjes,
Jelte :)

**Comment by driezie** [comment]
> This is a duplicate of an existing issue check issue #14

**Comment by driezie** [comment]
> This issue has been fixed in commit 737593b  by @driezie
