### ISSUE TITLE
in de form gebruik je bij de method _POST

### ISSUE THREAD

**Issue by Mossati** [driezie/the-startup-responsive-interactieve-website#16]
Haal de "_" weg bij de POST

**Comment by driezie** [comment]
Bedankt. Dit zal ik bij de volgende commit toepassen.

Beschrijf even volgende keer door middel van de issue template wat de issue is bedankt!!!

Groetjes,
Jelte :)

**Comment by driezie** [comment]
> This issue has been fixed in commit 737593b  by @driezie
