### ISSUE TITLE
Input type "phonenumber" is niet correct

### ISSUE THREAD

**Issue by Mossati** [driezie/the-startup-responsive-interactieve-website#17]
Gebruik "tel' als de input type

**Comment by driezie** [comment]
> This is a duplicate of an existing issue check issue #18 

Beschrijf even volgende keer door middel van de issue template wat de issue is bedankt!!!

Groetjes,
Jelte :)

**Comment by driezie** [comment]
> This issue has been fixed in commit 737593b  by @driezie
