### ISSUE TITLE
Slash achter elementen 

### ISSUE THREAD

**Issue by EBok1** [driezie/the-startup-responsive-interactieve-website#19]
Slash achter achter element is overbodig, zou je eventueel weg kunnen halen. 
https://github.com/driezie/the-startup-responsive-interactieve-website/blob/c757c86dacbe9f374bf56f7ed9bcc88661419380/index.html#L4

**Comment by driezie** [comment]
Thanks voor de suggestie maar dit heb ik normaal als default staan om mijn template maar goeie feedback!

Groetjes,
Jelte :)
