### ISSUE TITLE
Label for niet gelinkt aan input

### ISSUE THREAD

**Issue by Lmikkers** [driezie/the-startup-responsive-interactieve-website#20]
https://github.com/driezie/the-startup-responsive-interactieve-website/blob/737593b170e6bc0d34ea033c47161b622157b07e/index.html#L89-L90

In de https://validator.w3.org/ check, zag ik een foutmelding over je `<label for="name">`. Je zegt dat je label for name is, alleen er is geen input met id name, zodat je deze kunt linken.

> Error: The value of the for attribute of the label element must be the ID of a non-hidden form control.

Je kunt voor de `<label for="name">` de input die erbij hoor een id geven: `<input id="name">`

**Comment by driezie** [comment]
aangepast!
