### ISSUE TITLE
Altje vergeten

### ISSUE THREAD

**Issue by DamianR2004** [driezie/the-startup-responsive-interactieve-website#7]
https://github.com/driezie/the-startup-responsive-interactieve-website/blob/9f6c7927d65aaa71d110af772ddbe4f718da3c4f/mobile-first-demo/index.html#L66

Alt vergeten

**Comment by driezie** [comment]
Fotos worden nog opnieuw gedaan. Heb dit eventjes met haast in elkaar geflanst

**Comment by driezie** [comment]
Altje toegepast! Bekijk laatste commit
