### ISSUE TITLE
Dubbel ID

### ISSUE THREAD

**Issue by DamianR2004** [driezie/the-startup-responsive-interactieve-website#9]
Er wordt nog een dubbel id gebruikt:
https://github.com/driezie/the-startup-responsive-interactieve-website/blob/9f6c7927d65aaa71d110af772ddbe4f718da3c4f/mobile-first-demo/index.html#L212

![](https://media1.tenor.com/m/LcBHoFvwg8UAAAAd/ruben-koet-koetlife.gif)

**Comment by driezie** [comment]
dit heb ik niet zelf gemaakt dit is een svg die ik heb gekregen
